### PR TITLE
fix(compatibility table): Add missing Arduino Nano 33 IoT compatibility

### LINKED ISSUE #56: Arduino Nano 33 IoT Not Compatible
### Is there an existing issue for this bug?

- [X] I have searched the issues and there is no existing issue for this bug.

### What development environment are you using?

Arduino IDE

### What board are you using?

Arduino Nano 33 IoT

### What part of CRSF for Arduino is this bug related to?

Compatibility Table

### Current behaviour

With the debug flag enabled. I get the following when calling crsf.begin()

```
[Serial Receiver | INFO]: Initialising... 
[Compatibility Table | DEBUG]: Board is Incompatible device
incompatible.
Incompatible device

[Serial Receiver | ERROR]: Devboard is not compatible.
```

### Expected behaviour

Expected crsf to begin.

### Steps to reproduce

Issue can be reproduced with the channels example.

### Additional information

Attempting to log the name that it is comparing against shows the name as empty.

```
    bool CompatibilityTable::isDevboardCompatible(const char *name)
    {
        // Debug.
        // Serial.print("[Compatibility Table | DEBUG]: Board is ");

        if (strcmp(name, deviceNames[DEVBOARD_IS_INCOMPATIBLE]) == 0)
        {
            // Debug.
            Serial.println("incompatible.");
            Serial.println(name);

            return false;
        }

        else
        {
            // Debug.
            // Serial.println("compatible.");

            return true;
        }

        // return strcmp(name, deviceNames[DEVBOARD_IS_INCOMPATIBLE]) != 0 ? true : false;
    }
```

### PR DESCRIPTION
**Pull request by Speshl**
Have not  tested as I have not received my CRSF compatible receiver, but it begins without the unsupported error and seems to act normally with no data connected.

### CODE REVIEW

**Comment by ZZ-Cat** [comment]
Would be an idea to wait until your receiver shows up, and wait until you have tested your Nano 33 IoT with that receiver.

I am also aware that your last commit isn't signed. Could you please enable [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on your side?  
My [contribution guidelines](https://github.com/ZZ-Cat/CRSFforArduino/blob/a00d47f2dab9574c1987b3214316239812bbe162/.github/CONTRIBUTING.md#a-few-notable-points) state that all commits _must_ be signed.

I have linked #56 to this PR and added both of them to the [Version 1.0.0](https://github.com/ZZ-Cat/CRSFforArduino/milestone/4) milestone.

**Comment by Speshl** [comment]
Sure it should be here Sunday. Just trying to read PWM signal that is coming out of my RC drift gyro and sending that back to my transmitter. Ultimately trying to get the signal back to a raspberry pi.  Will keep you posted as I make progress to move this PR along.  Am looking into the commit signature now to get that resolved.

**Comment by ZZ-Cat** [comment]
Excellent.  
Your last commit shows up as 'verified'. However, you're still "merge blocked" because your previous commits in this PR are 'unverified' and the branch protection I have in place requires that _all_ commits in a Pull Request to the Main-Trunk need to be verified.

I know it can be a pain to set up, and reverting commits in GitHub isn't as straightforward as it could be.

There are three options you can do here:

1. [Revert](https://docs.github.com/en/desktop/managing-commits/reverting-a-commit-in-github-desktop) all of your commits, one-by-one, and redo them, so that they come up as 'verified';
2. If the first option fails, this Pull Request will need to be closed (thus, being rejected) and you will need to submit a new Pull Request _with all_ commits being verified; or...
3. At _my_ discretion,  I _can_ temporarily bypass my own branch protection rules, due to the fact that your last commit is verified.  
  This is also done as a one-off thing per individual, and it's done with the expectation that future commits from you _are_ verified. Any future Pull Requests you make with 'unverified' commits will automatically be rejected.  
  I will only do this part as an absolute last resort (IE the other two options are unsuccessful), as the desired path is _every_ commit to CRSF for Arduino is verified, for the sake of consistency.

**Comment by Speshl** [comment]
Sorry, don't usually check in to open repos, so it isn't something I have really messed with.  But it should be fine now since I (kinda) know what it is now and have it setup for this pc.  I can close this pull request and will reopen once I get my receiver, so I can verify there are no other changes needed to get my board to work.

**Comment by Speshl** [comment]
Looks like there is still something else happening. Getting an error related to the RX and TX pins not being set. But I can only see that error if debug mode is turned on.

Get the message when using the constructor with and without RX and TX pin specifications.

```
[Compatibility Table | DEBUG]: Board is Arduino Nano 33 IoT
Done.
ready
32855
starting crsf
[Serial Receiver | INFO]: Initialising... 
[Serial Receiver | ERROR]: RX and TX pins are not set.
```

**Comment by ZZ-Cat** [comment]
>  I can close this pull request and will reopen once I get my receiver, so I can verify there are no other changes needed to get my board to work.

Nah, keep this PR open. I'll rebase it onto another branch later on, and then squash it into either the Version 1.0.0 Tracking branch or the Main Trunk later on. Still learning how to use GitHub myself, and I could do with some practice here.

Anyway...

> Looks like there is still something else happening. Getting an error related to the RX and TX pins not being set. But I can only see that error if debug mode is turned on.
> 
> Get the message when using the constructor with and without RX and TX pin specifications.
> 
> ```
> [Compatibility Table | DEBUG]: Board is Arduino Nano 33 IoT
> Done.
> ready
> 32855
> starting crsf
> [Serial Receiver | INFO]: Initialising... 
> [Serial Receiver | ERROR]: RX and TX pins are not set.
> ```

That seems a bit odd. 🤔  
Is this happening in the example sketches? If not that, what's your source code that got you to this looking like?  
'Cause, by rights, it shouldn't be happening at all. The underlying constructor in the Serial Receiver layer is called automatically, when you set up the Sketch Layer constructor like so:
```cpp
#define SERIAL_RX_PIN 0 // Set SERIAL_RX_PIN to the pin that the CRSF receiver's TX pin is connected to.
#define SERIAL_TX_PIN 1 // Set SERIAL_TX_PIN to the pin that the CRSF receiver's RX pin is connected to.

CRSFforArduino crsf = CRSFforArduino(SERIAL_RX_PIN, SERIAL_TX_PIN);
```
:point_up_2: That right there should automatically define the pins for you, and when you go to call `CRSFforArduino::begin()` in your `setup()`, it should work with impunity.

**Comment by ZZ-Cat** [comment]
Also, I took the liberty of adding in the PlatformIO side of the Nano 33 IoT target, and converting your PR to a draft, given we're still ironing out the kinks here. =^/.~=

**Comment by Speshl** [comment]
Ya I agree it looks like the pins should be set, but still gives the error message. 🤷‍♂️   Able to reproduce with the telemetry example.

**Comment by ZZ-Cat** [comment]
That's very strange, because it compiles _and works_ well on my Adafruit Metro M0 Express, Feather M0 Bluefruit LE, and my Arduino Zero (both USB ports).  
Thar all using the same SAMD21 chipset as what's in your Nano 33 IoT. So, I'm not entirely sure what's going on there on your end.


To be fair, I _did_ use PlatformIO to build and test the aforementioned targets.
I'll try it with the legacy Arduino IDE on my end and see if that changes anything... by rights, it shouldn't. But, hey... Stranger Things have happened...

**Comment by ZZ-Cat** [comment]
# Update

## Test source code

### Arduino sketch

```cpp
#include <new>
#include "CRSFforArduino.hpp"

#define SERIAL_RX_PIN 0
#define SERIAL_TX_PIN 1

using namespace std;

CRSFforArduino *crsf = nullptr;

void setup()
{
  Serial.begin(115200);
  while (!Serial)
  {
    ;
  }

  crsf = new(nothrow) CRSFforArduino(SERIAL_RX_PIN, SERIAL_TX_PIN);
  if (crsf != nullptr)
  {
    if (!crsf->begin())
    {
      delete crsf;
      crsf = nullptr;
      Serial.println("CRSF for Arduino failed to initialise.");
    }
    else
    {
      Serial.println("CRSF for Arduino is running.");
    }
  }
  else
  {
    Serial.println("Not enough memory to create CRSF for Arduino instance.");
  }
}

void loop()
{
  if (crsf != nullptr)
  {

    crsf->update();

    static uint32_t start = millis();

    // Compensate for rollover.
    if (millis() < start)
    {
      start = millis();
    }

    // Terminate after a certain amount of run time.
    if (millis() - start >= 5000)
    {
      crsf->end();
      delete crsf;
      crsf = nullptr;

      Serial.print("CRSF for Arduino terminated at ");
      Serial.print(millis());
      Serial.println(" ms.");
    }
  }
}
```

### Configuration

```cpp
/**
 * @file CFA_Config.hpp
 * @author Cassandra "ZZ Cat" Robinson (nicad.heli.flier@gmail.com)
 * @brief This is the configuration file for CRSF for Arduino.
 * @version 0.5.0
 * @date 2023-11-1
 *
 * @copyright Copyright (c) 2023, Cassandra "ZZ Cat" Robinson. All rights reserved.
 *
 * @section License GNU General Public License v3.0
 * This header file is a part of the CRSF for Arduino library.
 * CRSF for Arduino is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CRSF for Arduino is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CRSF for Arduino.  If not, see <https://www.gnu.org/licenses/>.
 * 
 */

#pragma once

#include <Arduino.h>

/* The following defines are used to configure CRSF for Arduino.
You can change these values to suit your needs. */

namespace crsfForArduinoConfig
{
/* CRSFforArduino version
Versioning is done using Semantic Versioning 2.0.0.
See https://semver.org/ for more information. */
#define CRSFFORARDUINO_VERSION       "0.5.0"
#define CRSFFORARDUINO_VERSION_DATE  "2023-11-1"
#define CRSFFORARDUINO_VERSION_MAJOR 0
#define CRSFFORARDUINO_VERSION_MINOR 5
#define CRSFFORARDUINO_VERSION_PATCH 0

/* RC Options
- RC_ENABLED: Enables or disables the RC API.
- RC_MAX_CHANNELS: The maximum number of RC channels to be received.
- RC_CHANNEL_MIN: The minimum value of an RC channel.
- RC_CHANNEL_MAX: The maximum value of an RC channel.
- RC_CHANNEL_CENTER: The center value of an RC channel.
- RC_INITIALISE_CHANNELS: Whether or not to initialise the RC channels to their center values.
- RC_INITIALISE_ARMCHANNEL: When enabled, the arm channel is set to its minimum value.
  - NB: This refers to the Aux1 channel and is intended for use with ExpressLRS receivers.
- RC_INITIALISE_THROTTLECHANNEL: When enabled, the throttle channel is set to its minimum value. */
#define CRSF_RC_ENABLED                    1
#define CRSF_RC_MAX_CHANNELS               16
#define CRSF_RC_CHANNEL_MIN                172
#define CRSF_RC_CHANNEL_MAX                1811
#define CRSF_RC_CHANNEL_CENTER             992
#define CRSF_RC_INITIALISE_CHANNELS        1
#define CRSF_RC_INITIALISE_ARMCHANNEL      1
#define CRSF_RC_INITIALISE_THROTTLECHANNEL 1

/* Flight Modes
Enables or disables the Flight Mode API.
When enabled, you are given an event-driven API that allows you to easily implement flight modes
and assign them to a switch on your controller.
Pro Tip: You can combine the Flight Mode API with the Telemetry API to send flight mode
information back to your controller. */
#define CRSF_FLIGHTMODES_ENABLED 0

/* Telemetry Options
- TELEMETRY_ENABLED: Enables or disables the Telemetry API.
- TELEMETRY_ATTITUDE_ENABLED: Enables or disables attitude telemetry output.
- TELEMETRY_BAROALTITUDE_ENABLED: Enables or disables barometric altitude telemetry output.
- TELEMETRY_BATTERY_ENABLED: Enables or disables battery telemetry output.
- TELEMETRY_FLIGHTMODE_ENABLED: Enables or disables flight mode telemetry output.
- TELEMETRY_GPS_ENABLED: Enables or disables GPS telemetry output.
- TELEMETRY_SIMULATE_ARBITRARY_VALUES: When enabled, arbitrary values are sent for telemetry. */
#define CRSF_TELEMETRY_ENABLED              1
#define CRSF_TELEMETRY_ATTITUDE_ENABLED     1
#define CRSF_TELEMETRY_BAROALTITUDE_ENABLED 1
#define CRSF_TELEMETRY_BATTERY_ENABLED      1
#define CRSF_TELEMETRY_FLIGHTMODE_ENABLED   0
#define CRSF_TELEMETRY_GPS_ENABLED          1

/* Debug Options
- DEBUG_ENABLED: Enables or disables debug output over the selected serial port. */
#define CRSF_DEBUG_ENABLED     1
#define CRSF_DEBUG_SERIAL_PORT Serial

/* All warnings and asserts below this point are to ensure that the configuration is valid. */

/* Compiler warning if both RC and Telemetry are disabled. */
#if CRSF_RC_ENABLED == 0 && CRSF_TELEMETRY_ENABLED == 0
#warning "Both CRSF_RC_ENABLED and CRSF_TELEMETRY_ENABLED are disabled. CRSF for Arduino will not do anything."
#endif

/* Static assert if Flight Modes are enabled, but RC is disabled. */
#if CRSF_FLIGHTMODES_ENABLED == 1 && CRSF_RC_ENABLED == 0
    static_assert(false, "CRSF_FLIGHTMODES_ENABLED is enabled, but CRSF_RC_ENABLED is disabled. Flight Modes require RC to be enabled.");
#endif

/* Static assert if all telemetry options are disabled.
Better to use CRSF_TELEMETRY_ENABLED instead. */
#if CRSF_TELEMETRY_ATTITUDE_ENABLED == 0 && CRSF_TELEMETRY_BAROALTITUDE_ENABLED == 0 && CRSF_TELEMETRY_BATTERY_ENABLED == 0 && CRSF_TELEMETRY_FLIGHTMODE_ENABLED == 0 && CRSF_TELEMETRY_GPS_ENABLED == 0
    static_assert(false, "All telemetry options are disabled. Set CRSF_TELEMETRY_ENABLED to 0 to disable telemetry instead.");
#endif

}; // namespace crsfForArduinoConfig
```

Debugging was also turned on in the Compatibility Table, by uncommenting the code in `hal::CompatibilityTable::getDevboardName()` here:
```cpp
const char *CompatibilityTable::getDevboardName()
{
    if (device.type.devboard >= DEVBOARD_COUNT)
    {
        // Debug.
        Serial.println("\r\n[Compatibility Table | FATAL ERROR]: Board index is out of bounds.");

        return deviceNames[DEVBOARD_IS_INCOMPATIBLE];
    }

    // Debug.
    Serial.print("\r\n[Compatibility Table | DEBUG]: Board is ");
    Serial.println(deviceNames[device.type.devboard]);

    return deviceNames[device.type.devboard];
}
```

## Test hardware

### Control board

- Adafruit Metro M4 Express

Every aspect of CRSF for Arduino in its current state is _known_ to work flawlessly on this board.  
Therefore, it is my point of reference for this test.

### Boards tested

- Adafruit Feather M0 Bluefruit LE
- Adafruit Metro M0 Express
- Arduino Zero (Native USB Port)

## Test environment

- **IDE:** Arduino v1.8.19.
- No connections other than the boards' native USB connection.
- CRSF for Arduino
  - Version: 0.5.0
  - Date: 2023-11-1
  - Branch: [pr/Speshl/57](https://github.com/Speshl/CRSFforArduino/tree/Main-Trunk)
  - Commit: d67b0a0184acf6ab9284e2d6cbd960914c123e53

## Alterations during the test

The _only_ change I made was prior to flashing the source code above to my Arduino Zero, I changed the `Serial` class prefix in all calls to `Serial.print()` and `Serial.println()` to `SerialUSB` to accommodate my Zero's native USB port, instead of using the on-board EDBG interface.

## Results

### Expected

```text
[Serial Receiver | INFO]: Initialising... 
[Compatibility Table | DEBUG]: Board is <Board name here>
Done.
CRSF for Arduino is running.
CRSF for Arduino terminated at <Total firmware execution time here> ms.
```

### Adafruit Metro M4 Express (Control Board)

```text
[Serial Receiver | INFO]: Initialising... 
[Compatibility Table | DEBUG]: Board is Adafruit Metro M4 Express
Done.
CRSF for Arduino is running.
CRSF for Arduino terminated at 10961 ms.
```

### Adafruit Feather M0 Express

```text
[Serial Receiver | INFO]: Initialising... 
[Compatibility Table | DEBUG]: Board is Adafruit Feather M0
Done.
CRSF for Arduino is running.
CRSF for Arduino terminated at 6843 ms.
```

### Adafruit Metro M0 Express

```text
[Serial Receiver | INFO]: Initialising... 
[Compatibility Table | DEBUG]: Board is Adafruit Metro M0 Express
Done.
CRSF for Arduino is running.
CRSF for Arduino terminated at 12605 ms.
```

### Arduino Zero

```text
[Serial Receiver | INFO]: Initialising... 
[Compatibility Table | DEBUG]: Board is Arduino Zero
Done.
CRSF for Arduino is running.
CRSF for Arduino terminated at 13314 ms.
```

## Conclusion

The boards I have tested here have yielded the same result as my control board.  
This is consistent with how CRSF for Arduino _should_ function.  
I did this to provide you with a solid frame of reference to what seems to be plaguing your Nano 33 IoT in terms of compatibility.

I have been unable to recreate your issue with the Nano 33 IoT with the hardware that I have available on-hand. Every board that I tested here (barring the Metro M4) uses the same SAMD21G18A chipset as your Nano 33 IoT. So, by rights, it _should not_ have made a difference, and I _should_ have been able to recreate the issue you're describing here.

### Where to from here?

This test proves to me that I need more context from you.
I would like you to recreate my test on your end, using your Nano 33 IoT.  
For this test, don't connect anything to the board itself other than the USB cable you need to flash the firmware.

Here is how to recreate and reproduce the test...
1. Copy the source code in the Arduino Sketch into a new sketch in the Arduino IDE.
2. Copy the configuration source code into `CFA_Config.hpp` located in `src/CRSFforArduino/src/`
3. In `src/CRSFforArduino/src/Hardware/CompatibilityTable/CompatibilityTable.cpp` find the commented out `Serial.print()` and `Serial.println()` functions, and uncomment them to enable them.
4. Back in your Arduino Sketch (that you copied from here), verify and upload it to your Nano 33 IoT.
5. Open up your Serial Monitor, once the upload is complete.
6. Wait about 5-to-10 seconds for the test to complete.
7. Copy all of what you're seeing in the Serial Monitor and post your results here.

## Additional

I'm _not_ gonna lie. This has me stumped equally as much as you.  
I don't know why the UART pins aren't being defined when CRSF for Arduino is initialised on your Nano 33 IoT.  

If you look at both constructors in the Serial Receiver Layer, you can see that the `_rxPin` and `_txPin` are initialised to their respective values.
```cpp
SerialReceiver::SerialReceiver()
{
    _rxPin = 0;
    _txPin = 1;
    board = new DevBoards();
    ct = new CompatibilityTable();

#if CRSF_RC_ENABLED > 0
    _rcChannels = new uint16_t[RC_CHANNEL_COUNT];
#if CRSF_FLIGHTMODES_ENABLED > 0
    _flightModes = new flightMode_t[FLIGHT_MODE_COUNT];
#endif
#endif
}

SerialReceiver::SerialReceiver(uint8_t rxPin, uint8_t txPin)
{
    _rxPin = rxPin;
    _txPin = txPin;
    board = new DevBoards();
    ct = new CompatibilityTable();

#if CRSF_RC_ENABLED > 0
    _rcChannels = new uint16_t[RC_CHANNEL_COUNT];
#if CRSF_FLIGHTMODES_ENABLED > 0
    _flightModes = new flightMode_t[FLIGHT_MODE_COUNT];
#endif
#endif
}
```

In the function `SerialReceiver::begin()`, the `_rxPin` and `_txPin` values are compared with their 'overrun' values of 255 (of which is set by default in the `SerialReceiver` class to ensure that their configuration is valid.  
This validity check is a redundancy, and likely should not return `false` when either of the two constructors are used.
```cpp
if (_rxPin == 0xffu && _txPin == 0xffu)
{
    // board->exitCriticalSection();

#if CRSF_DEBUG_ENABLED > 0
    // Debug.
    CRSF_DEBUG_SERIAL_PORT.println("\n[Serial Receiver | ERROR]: RX and TX pins are not set.");
#endif
    return false;
}
```

If you look up into the Sketch Layer (which exposes CRSF for Arduino's API to your sketch), you can see how the constructors are called. Additionally, there is a compiler warning when `CRSF_RC_ENABLED` and `CRSF_TELEMETRY_ENABLED` are both set to `0` (IE disabled).
```cpp
CRSFforArduino::CRSFforArduino()
{
#if CRSF_RC_ENABLED > 0 || CRSF_TELEMETRY_ENABLED > 0
    _serialReceiver = new SerialReceiver();
#endif
}

CRSFforArduino::CRSFforArduino(uint8_t rxPin, uint8_t txPin)
{
#if CRSF_RC_ENABLED > 0 || CRSF_TELEMETRY_ENABLED > 0
    _serialReceiver = new SerialReceiver(rxPin, txPin);
#else
    // Prevent compiler warnings
    (void)rxPin;
    (void)txPin;
#endif
}
```

When you go to start CRSF for Arduino, the Sketch Layer call to `CRSFforArduino::begin()` calls the underlying Serial Receiver Layer function `SerialReceiver::begin()` like so...
```cpp
bool CRSFforArduino::begin()
{
#if CRSF_RC_ENABLED > 0 || CRSF_TELEMETRY_ENABLED > 0
    return _serialReceiver->begin();
#else
    // Return false if RC is disabled
    return false;
#endif
}
```

As much as I would _like_ to draw the conclusion that your pin configuration is not valid, I feel like this is somewhat inaccurate, especially if you're already using the default `Serial1` UART on your Nano 33 IoT to facilitate CRSF for Arduino.  
This is starting to look like something a bit more obscure, to which I am _yet_ to figure out.

**Comment by Speshl** [comment]
So I followed your steps and I am getting the following now when running, which looks correct except for the info comment for serial receiver initializing.
```
05:13:40.311 -> [Compatibility Table | DEBUG]: Board is Arduino Nano 33 IoT
05:13:40.311 -> CRSF for Arduino is running.
05:13:45.284 -> CRSF for Arduino terminated at 6992 ms.
```

**Comment by Speshl** [comment]
Here is my manual test code that does send out a value "correctly".  I can see the value on my MT12 transmitter, as well as on telemetry monitor in my python and golang apps monitoring telemetry on my raspberry pi.  If I switch to the telemetry example you provide with generated GPS data turned on, I am unable to see any data coming out.  For my use case the below example (when updated with actual input data) will suffice.  So if this is just an issue of me using this package wrong, then no pressure to help. I got what I need working.

```c++
int16_t loopValue = -180;


void setup() {
  //set up the serial monitor, pin mode, and external interrupt.
  Serial.begin(420000);
  // while(!Serial){
  //   ;
  // }
  Serial1.begin(420000); 

  delay(100);
  Serial.println("ready");
}

void loop() {
  if(loopValue > 180) {
    loopValue = -180;
  }

  int yawRadians = loopValue * 174; //(value * 10000) / 3.14159 / 180 

  byte msb = (yawRadians >> 8) & 0xFF; // Most significant byte (MSB)
  byte lsb = yawRadians & 0xFF; // Least significant byte (LSB)
  uint8_t preCrc8Data[] = {0x1E,0x00,0x00,0x00,0x00,msb,lsb};
  uint8_t crc8 = GenerateCrc8Value(preCrc8Data, sizeof(preCrc8Data));

  uint8_t combined[] = {0xC8,0x08,0x1E,0x00,0x00,0x00,0x00,msb,lsb,crc8}; //https://crccalc.com/
  Serial1.write(combined, sizeof(combined));
  delay(10);
  loopValue++;
}

uint8_t crc8_dvb_s2(uint8_t crc, uint8_t a) {
  crc = crc ^ a;
  for (uint8_t ii = 0; ii < 8; ++ii) {
    if (crc & 0x80) {
      crc = (crc << 1) ^ 0xD5;
    } else {
      crc = crc << 1;
    }
  }
  return crc & 0xFF;
}

uint8_t GenerateCrc8Value(uint8_t* data, size_t dataSize) {
  uint8_t crc = 0;
  for (size_t i = 0; i < dataSize; ++i) {
    crc = crc8_dvb_s2(crc, data[i]);
  }
  return crc;
}

bool ValidateFrame(uint8_t* frame, size_t frameSize) {
  uint8_t crc = GenerateCrc8Value(frame + 2, frameSize - 3);
  return crc == frame[frameSize - 1];
}
```

**Comment by ZZ-Cat** [comment]
> So I followed your steps and I am getting the following now when running, which looks correct except for the info comment for serial receiver initializing.
> ```
> 05:13:40.311 -> [Compatibility Table | DEBUG]: Board is Arduino Nano 33 IoT
> 05:13:40.311 -> CRSF for Arduino is running.
> 05:13:45.284 -> CRSF for Arduino terminated at 6992 ms.
> ```

Good. That tells me the test worked as expected.

The reason why you aren't seeing the Serial Receiver info message is because you have `CRSF_DEBUG_ENABLED` set to `0` in `CFA_Config.hpp`

**Review by ZZ-Cat — DISMISSED** [review]
Right-oh. I'mma go ahead and merge this into the `Main-Trunk`.  
Looks to me like it's all working well.

**Pull request merged**
