### PR TITLE
feat(serial receiver interface): :sparkles: Introduce three new callbacks

### PR DESCRIPTION
**Pull request by ddanilchenko**
- on connection down. performs if there is no data received within last CRSF_FAILSAFE_STAGE1_MS (300 ms)
 - on connection up. performs when connection was previously in down state and new data received successfully
 - raw data received. performs when new data received. can be used in case you need to deal with the raw data

```
 ...
   outputSerial.begin(CRSF_BAUD_RATE, SERIAL_8N1, TX_PIN2, RX_PIN2);

    // Initialise CRSF for Arduino.
    crsfInput0 = new CRSFforArduino(&inputSerial0, RX_PIN0, TX_PIN0);
    if (!crsfInput0->begin())
    {
        crsfInput0->end();
        delete crsfInput0;
        crsfInput0 = nullptr;

        Serial.println("CRSF0 for Arduino initialisation failed!");
        while (1)
        {
            delay(10);
        }
    }
   
    rcChannelCount = rcChannelCount > crsfProtocol::RC_CHANNEL_COUNT ? crsfProtocol::RC_CHANNEL_COUNT : rcChannelCount;

    crsfInput0->setLinkStatisticsCallback(onLinkStatisticsUpdate0);

    crsfInput0->setRawDataCallback(onRawDataCallback0);
    crsfInput0->setLinkUpCallback(onLink0UpCallback);
    crsfInput0->setLinkDownCallback(onLink0DownCallback);

...

void onLinkStatisticsUpdate0(serialReceiverLayer::link_statistics_t linkStatistics)
{
    if (millis() - lastUpdateLQ0 >= LINK_QUALITY_UPDATE_INTERVAL)
    {
        lastUpdateLQ0 = millis();
        Serial.print("Link Statistics0: ");
        Serial.print("RSSI: ");
        Serial.print(linkStatistics.rssi);
        Serial.print(", Link Quality: ");
        Serial.print(linkStatistics.lqi);
        Serial.print(", Signal-to-Noise Ratio: ");
        Serial.print(linkStatistics.snr);
        Serial.print(", Transmitter Power: ");
        Serial.println(linkStatistics.tx_power);
    }
}

...

void onRawDataCallback0(int8_t byteReceived)
{
    Serial.println("primary channel passthrough");
    outputSerial.write(byteReceived);
}

...

void onLink0DownCallback()
{
  Serial.println("main link is down");
}

void onLink0UpCallback()
{
    Serial.println("main link is up");
}

```

### CODE REVIEW

**Comment by ZZ-Cat** [comment]
Before I run my CodeQL and Quality Control workflows on this, can you change the base branch from `Main-Trunk` to `Version-1.1.0-Development`?

Also, in your Pull Request description, can you clarify what each callback does and their purpose?

**Comment by ddanilchenko** [comment]
> Before I run my CodeQL and Quality Control workflows on this, can you change the base branch from `Main-Trunk` to `Version-1.1.0-Development`?
> 
> Also, in your Pull Request description, can you clarify what each callback does and their purpose?

done. modified the initial comment for the PR. please have as look. a few words about onrawdatareceived. the main purpose of it is to add possibility of handling raw data received by the instance of the SerialReceiver class. in my case i used it to implement seamless integration with fc, e.g. read data from rx, handle crsf packages and bypass raw data to fc.

**Review by ZZ-Cat — CHANGES_REQUESTED** [review]
## Defects detected

My Defect Detector has pinged you in the copy constructor for [`SerialReceiver.cpp`](../../blob/46d993ed73d14db34bd294f7e1dfcb8994ed53d7/src/SerialReceiver/SerialReceiver.cpp#L152)

### Summary of defects

```shell
src/SerialReceiver/SerialReceiver.cpp:152: [medium:warning] Member variable 'SerialReceiver::_rawDataCallback' is not assigned a value in 'SerialReceiver::operator='. [operatorEqVarError]
src/SerialReceiver/SerialReceiver.cpp:152: [medium:warning] Member variable 'SerialReceiver::_linkUpCallback' is not assigned a value in 'SerialReceiver::operator='. [operatorEqVarError]
src/SerialReceiver/SerialReceiver.cpp:152: [medium:warning] Member variable 'SerialReceiver::_linkDownCallback' is not assigned a value in 'SerialReceiver::operator='. [operatorEqVarError]
```

### Full error message

Screenshot from 2024-08-31 10-07-40

## Possible solution

Consider assigning values to your three callbacks in `SerialReceiver::operator=` copy constructor.

**Example:**

```cpp
namespace serialReceiverLayer
{
    SerialReceiver &SerialReceiver::operator=(const SerialReceiver &serialReceiver)
    {

        /* ... */

        _rawDataCallback = serialReceiver._rawDataCallback;
        _linkUpCallback = serialReceiver._linkUpCallback;
        _linkDownCallback = serialReceiver._linkDownCallback;

        /* ... */

    }
}
```

**Review by ZZ-Cat — APPROVED** [review]
Thank you for your contribution here, it's greatly appreciated.  
Everything has passed with flying colours. =^/.^=

So, Imma go ahead and update the PR name to bring it in-line with my Conventional Commits and then merge your Pull Request.

**Pull request merged**
