### PR TITLE
feat(devboard): Add support for RP2040

### LINKED ISSUE #52: Support for Raspberry Pico
### Minimum requirements

- [X] Core clock speed is 48 MHz or faster?
- [X] Is the CPU an ARM Cortex M0+ or later?
- [X] Is the host microcontroller's UART peripheral able to support 420,000 (or higher) baud rate(s)?
- [X] Is your development board currently supported in the Arduino IDE?

### What development board would you like me to add?

Would it be possible to add RP2040 support? eg Waveshare RP2040 Zero or any other RP2040 based DevBoard like the original Raspberry Pi Pico.
Thanks!

### PR DESCRIPTION
**Pull request by ZZ-Cat**
## Overview

This Pull Request introduces a new architecture, plus support for two new development boards:

- Arduino RP2040 Architecture
  - Arduino Nano RP2040 Connect
  - Raspberry Pi Pico RP2040

## Additional notes

As it turns out, the existing Raspberry Pi Pico RP2040 support that PlatformIO uses is based on MBed. Not [Earle Philhower's Arduino Pico](https://github.com/earlephilhower/arduino-pico) like I had previously thought.  
This means that the vast majority of RP2040 targets are still _not currently_ supported in PlatformIO.

There is a [Pull Request](https://github.com/platformio/platform-raspberrypi/pull/36) that's currently open and being actively worked on, to add Earle Philhower's RP2040 package to PlatformIO. When that Pull Request is merged, I will start adding in the rest of the RP2040 targets. But, until then, you guys are (unfortunately) stuck with two RP2040 targets.

### CODE REVIEW

**Comment by ZZ-Cat** [comment]
Right-oh, @PeterCasa. You're up.  
Can you check out this Pull Request's [development branch](https://github.com/ZZ-Cat/CRSFforArduino/tree/ZZ-Cat/issue52) and flash one of CRSF for Arduino's [examples](https://github.com/ZZ-Cat/CRSFforArduino/tree/ZZ-Cat/issue52/examples) to one of your RP2040 development boards, and let me know how that goes for you?  
Thanks in advance.

**Comment by kingfisher09** [comment]
Does this pull request also add support for the Arduino RP2040 Connect? If so I could try it out in the Arduino IDE if that would be helpful.

**Comment by ZZ-Cat** [comment]
> Does this pull request also add support for the Arduino RP2040 Connect? If so I could try it out in the Arduino IDE if that would be helpful.

Yup. Arduino RP2040 Connect was added in 7181229c68a209fda17f7fbed4208ac4dee548b4.

You're very welcome to test this Pull Request and let me know how it goes.

**Comment by kingfisher09** [comment]
Great! I found another library that works for rp2040 but it doesn't have telemetry so I'm keen to get your one working on my project!

**Comment by ZZ-Cat** [comment]
Yeha. That's one of the advantages CRSF for Arduino brings to the table: Full RC and telemetry support.

**Comment by PeterCasa** [comment]
@ZZ-Cat: sorry, I'm a little late to the party, didn't find some spare time. I've just tested your excellent piece of code and it works flawlessly on a WeAct RP2040 Dev board (set the board in arduino to "Raspberry Pi Pico"), right out of the box. Thank you very much!

**Comment by ZZ-Cat** [comment]
You're very welcome. =^/.^=

**Pull request merged**
